const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const dataModule = source => 'data:text/javascript;base64,' + Buffer.from(source).toString('base64');
(async () => {
  const api = dataModule(fs.readFileSync(path.join(__dirname, '../frontend/api.js'), 'utf8'));
  const source = fs.readFileSync(path.join(__dirname, '../frontend/article-markdown.js'), 'utf8').replace("'./api.js'", JSON.stringify(api));
  const { renderArticleBlocks } = await import(dataModule(source));
  const renderArticleMarkdown = text => renderArticleBlocks(text).map(part => part.html).join('');
  const text = '> IP 解决“数据怎么送到一台主机”\n\n---\n\n## 1. 端口号\n\n传输层最重要的抽象之一就是：\n\n```\nIP 地址 + 端口号\n```\n\nIP 定位主机，端口定位进程/服务。\n\n端口号是 16 bit：\n\n```\n0 ~ 65535\n```';
  const html = renderArticleMarkdown(text);
  assert.match(html, /<blockquote>/);assert.match(html, /<hr>/);
  assert.match(html, /<h2>1\. 端口号<\/h2>/);
  assert.match(html, /<pre><code>IP 地址 \+ 端口号<\/code><\/pre>/);
  assert.match(html, /<pre><code>0 ~ 65535<\/code><\/pre>/);
  assert(!html.includes('```'));
  console.log('PASS reported Markdown example renders quotes, headings, rules and fenced code');
  const styles=renderArticleMarkdown('**粗体** 和 *强调* 与 `**原样代码**`\n下一行\n\n- 项目一\n- 项目二\n  - 子项目\n\n1. 有序列表\n2. 第二项\n\n| 列一 | 列二 |\n| --- | --- |\n| 内容 | 值 |');
  for(const tag of ['strong','em','code','ul','ol','table','th','td'])assert(styles.includes('<'+tag),tag);
  assert(styles.includes('<code>**原样代码**</code>'));
  assert(styles.includes('<br>下一行'));
  console.log('PASS common inline markup, nested lists, tables and line breaks');
  const unsafe=renderArticleMarkdown('<img src=x onerror=alert(1)>\n\n<script>alert(1)</script>\n\n[x](javascript:alert)\n\n![图片](https://example.com/image.png)\n\n```html\n<script>not executable</script>\n```');
  assert(!unsafe.includes('<img'));assert(!unsafe.includes('<script'));assert(!unsafe.includes('href="javascript:'));
  assert(unsafe.includes('&lt;script&gt;'));
  const linked=renderArticleMarkdown('[网站](https://example.com)');
  assert(linked.includes('rel="noopener noreferrer"'));
  assert.equal(renderArticleMarkdown(''), '');
  assert.equal(renderArticleMarkdown('日本語\r\n次の行'),'<p>日本語<br>次の行</p>');
  console.log('PASS source HTML is escaped; unsafe URLs and remote images cannot execute or load');
  assert.equal(typeof renderArticleBlocks, 'function', 'live editing needs source ranges for rendered blocks');
  const original = '# 标题\r\n\r\n日本語 **原文**\r\n次の行\r\n\r\n```js\r\n1 < 2\r\n```\r\n';
  const parts = renderArticleBlocks(original);
  assert.deepEqual(parts.map(part => original.slice(part.start, part.end)), ['# 标题', '日本語 **原文**\r\n次の行', '```js\r\n1 < 2\r\n```']);
  assert.deepEqual(renderArticleBlocks(''), []);
  assert.equal(renderArticleBlocks('- 一\n  - 二\n\n- 三')[0].html, '<ul><li><p>一</p><ul><li><p>二</p></li></ul></li><li><p>三</p></li></ul>');
  console.log('PASS live block ranges preserve original CRLF, nested lists and fenced code');
})().catch(error=>{console.error(error.message);process.exitCode=1;});
