// Native browser UI tests; all API responses are local fixtures, never real providers.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { launchBrowser } = require('./browser_test_helper.cjs');
const root = path.resolve(__dirname, '..');
const ids = ['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'];
const now = '2026-10-03T10:00:00+00:00';
const articles = new Map(ids.map((id,i)=>[id,{id,title:i?'雨の日の手紙':'東京の小さな喫茶店',content:('日本語の文章。\n次の行です。\n').repeat(70),revision:1,created_at:now,updated_at:now}]));
let account = {id:1,username:'reader'};
let ttsCalls=0, explainCalls=0, failSave=false;
const wav=Buffer.alloc(44+4800);
wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);
wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);
wav.writeUInt32LE(24000,24);wav.writeUInt32LE(48000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);
wav.write('data',36);wav.writeUInt32LE(4800,40);
const server = http.createServer(async (req,res)=>{
  const url=new URL(req.url,'http://localhost');
  const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(status===204?'':JSON.stringify(data));};
  if(url.pathname==='/api/auth/me')return json(account||{detail:'login'},account?200:401);
  if(url.pathname==='/api/auth/config')return json({auth_required:false});
  if(url.pathname==='/api/history')return json([]);
  if(url.pathname==='/api/engines')return json([{id:'edge',name:'Edge TTS',is_free:true,default_voice:'ja-JP-NanamiNeural',min_text_length:1,max_text_length:1000,request_timeout_seconds:30,voices:[{id:'ja-JP-NanamiNeural',name:'七海'}]}]);
  if(url.pathname==='/api/copilot/models')return json({models:[{id:'test',name:'Local mock',default:true,modes:[{id:'direct',name:'标准'}]}]});
  if(url.pathname==='/api/explain'){explainCalls++;return json({explain_key:'mock',explanation:'只解释已提交的原文。',cached:true,messages:[]});}
  if(url.pathname==='/api/tts'||url.pathname==='/api/tts/'+'c'.repeat(64)){
    if(req.method==='POST')ttsCalls++;
    res.writeHead(200,{'Content-Type':'audio/wav','X-Cache-Key':'c'.repeat(64)});return res.end(wav);
  }
  if(url.pathname.startsWith('/api/articles')){
    if(!account)return json({detail:'login'},401);
    let raw='';for await(const chunk of req)raw+=chunk;
    const body=raw?JSON.parse(raw):null;
    const id=url.pathname.split('/')[3];
    if(req.method==='GET'&&!id){const q=url.searchParams.get('q')||'';return json([...articles.values()].filter(a=>(a.title+a.content).includes(q)).map(({content,...a})=>({...a,character_count:[...content].length})));}
    if(req.method==='POST'){if(!articles.has(body.id))articles.set(body.id,{...body,revision:1,created_at:now,updated_at:now});return json(articles.get(body.id),201);}
    if(!articles.has(id))return json({detail:'deleted'},404);
    if(req.method==='GET')return json(articles.get(id));
    if(req.method==='DELETE'){articles.delete(id);return json(null,204);}
    if(req.method==='PUT'){
      if(failSave)return json({detail:'离线测试：保存失败'},503);
      const a=articles.get(id);if(body.revision!==a.revision)return json({detail:'版本冲突'},409);
      Object.assign(a,body,{revision:a.revision+1,updated_at:new Date().toISOString()});return json(a);
    }
  }
  const file=path.resolve(root,'frontend',url.pathname==='/'?'index.html':url.pathname.slice(1));
  if(file.startsWith(path.join(root,'frontend')+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()){
    res.writeHead(200,{'Content-Type':{'.js':'text/javascript','.html':'text/html','.css':'text/css'}[path.extname(file)]||'text/plain'});return res.end(fs.readFileSync(file));
  }
  json({detail:'missing'},404);
});
let browser;
(async()=>{
  try{
    await new Promise(r=>server.listen(0,'127.0.0.1',r));
    browser=await launchBrowser({profilePrefix:'tts-articles-',exceptionDescriptions:true});
    const {send,evaluate,wait,exceptions}=browser;
    await send('Runtime.enable');await send('Page.enable');
    await send('Emulation.setFocusEmulationEnabled',{enabled:true});
    await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.confirm=()=>true;if(!sessionStorage.getItem('testedLegacyWorkspace')){sessionStorage.setItem('testedLegacyWorkspace','true');localStorage.setItem('tts_workbench_v1:account_1',JSON.stringify({opened:['${ids[0]}'],selected:'${ids[0]}',positions:{'${ids[0]}':160}}));}`});
    await send('Emulation.setDeviceMetricsOverride',{width:1440,height:960,deviceScaleFactor:1,mobile:false});
    await send('Page.navigate',{url:`http://127.0.0.1:${server.address().port}/`});
    await wait("document.body?.dataset.ready==='true'");
    assert.equal(await evaluate("!!document.getElementById('articleLibraryBtn')"),false);
    assert.equal(await evaluate("document.getElementById('aiPanelBtn').textContent"),'阅读工作台');
    await wait(`document.getElementById('article-panel-${ids[0]}')?.hidden===false`);
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').hidden`),true);
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-mode-edit').click()`);
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').scrollTop`),160);
    console.log('PASS legacy workspace positions retain source scroll and open in rendered reading mode');
    await evaluate("document.getElementById('workspaceAddBtn').click()");
    await wait("document.querySelectorAll('[data-article-open]').length===2");
    console.log('PASS account library opens');
    const select = async id => evaluate(`document.querySelector('[data-workspace-tab="${id}"]').click()`);
    const open = async id => {
      await wait(`!!document.querySelector('[data-article-open="${id}"]')`);
      await evaluate(`document.querySelector('[data-article-open="${id}"]').click()`);
      await wait(`document.getElementById('article-panel-${id}')?.hidden===false`);
    };
    const input = async (id,selector,value) => evaluate(`(()=>{const node=document.getElementById('article-panel-${id}');if('${selector}'==='.article-body')node.querySelector('.article-mode-edit').click();const el=node.querySelector('${selector}');el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    await open(ids[0]);
    await input(ids[0],'.article-title-input','東京の読書ノート');
    await input(ids[0],'.article-body','保存中の文章。\n次の行です。\n'+ '長い原文です。\n'.repeat(120));
    await evaluate(`document.getElementById('body-${ids[0]}').scrollTop=480`);
    const scroll=await evaluate(`document.getElementById('body-${ids[0]}').scrollTop`);
    assert(scroll>0);
    await select('library');await open(ids[1]);await select(ids[0]);
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').scrollTop`),scroll);
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='已保存'`);
    assert.equal(articles.get(ids[0]).title,'東京の読書ノート');
    await select('library');await open(ids[0]);
    assert.equal(await evaluate(`document.querySelectorAll('[data-workspace-tab="${ids[0]}"]').length`),1);
    assert.equal(await evaluate("[...document.querySelectorAll('.article-editor')].filter(n=>!n.hidden).length"),1);
    console.log('PASS independent edits, switch flush, scroll retention and duplicate-open focus');
    await select('ai');
    assert.equal(await evaluate(`JSON.parse(localStorage.getItem('tts_workbench_v1:account_1')).positions['${ids[0]}'].editScroll`),scroll);
    await evaluate("document.body.dataset.ready='reloading'");await send('Page.reload');
    await wait("document.body?.dataset.ready==='true'");
    await wait(`!!document.querySelector('[data-workspace-tab="${ids[0]}"]')`);
    await wait("document.querySelector('[data-workspace-tab=\"ai\"]').getAttribute('aria-selected')==='true'");
    await select(ids[0]);
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').scrollTop`),scroll);
    console.log('PASS reading position survives switching to AI and refreshing while the article is hidden');

    await evaluate("document.getElementById('textInput').value='未发送草稿';window.confirm=()=>false");
    const selected='保存中の文章。\n次の行です。';
    await evaluate(`(()=>{const body=document.getElementById('body-${ids[0]}');body.focus();body.setSelectionRange(0,${selected.length});body.dispatchEvent(new Event('select'));document.getElementById('article-panel-${ids[0]}').querySelector('.article-fill').click();})()`);
    assert.equal(await evaluate("document.getElementById('textInput').value"),'未发送草稿');
    await evaluate(`window.confirm=()=>true;document.getElementById('article-panel-${ids[0]}').querySelector('.article-fill').click()`);
    assert.equal(await evaluate("document.getElementById('textInput').value"),selected);
    assert.equal(ttsCalls,0);assert.equal(explainCalls,0);
    assert.equal(await evaluate("document.getElementById('explainTarget').textContent"),'发送一段文本，开始阅读。');
    await evaluate("document.getElementById('generateBtn').click()");
    await wait("document.querySelectorAll('.user-message').length===1");
    await wait("document.getElementById('explainMessages').textContent.includes('只解释')");
    assert.equal(ttsCalls,1);assert.equal(explainCalls,1);
    await select('ai');
    await evaluate("document.getElementById('explainChatInput').value='保留的问题草稿'");
    await select(ids[1]);await input(ids[1],'.article-body','右侧文章不能成为 AI 对象。');await select('ai');
    assert.equal(await evaluate("document.getElementById('explainChatInput').value"),'保留的问题草稿');
    assert.equal(await evaluate("document.getElementById('explainTarget').textContent"),selected);
    assert.equal(explainCalls,1);
    console.log('PASS selection confirmation, preserved newlines, explicit TTS submission and isolated AI context');

    await select(ids[0]);
    failSave=true;
    await input(ids[0],'.article-body','需要恢复的本地草稿。\n'+ '草稿阅读位置\n'.repeat(100));
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='保存失败'`);
    await evaluate(`document.getElementById('body-${ids[0]}').scrollTop=320`);
    await evaluate("document.body.dataset.ready='reloading'");
    await send('Page.reload');
    await wait("document.body?.dataset.ready==='true'");
    await wait(`document.getElementById('article-panel-${ids[0]}')?.hidden===false`);
    assert((await evaluate(`document.getElementById('body-${ids[0]}').value`)).startsWith('需要恢复'));
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').scrollTop`),320);
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='保存失败'`);
    failSave=false;
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-retry').click()`);
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='已保存'`);
    console.log('PASS refresh restores opened tabs, selection, local draft and reading position; retry saves');

    await evaluate(`document.querySelector('[data-close-article="${ids[1]}"]').click()`);
    assert(articles.has(ids[1]));
    await select('library');await open(ids[1]);
    await evaluate(`document.getElementById('article-panel-${ids[1]}').querySelector('.article-delete').click()`);
    await wait(`!document.querySelector('[data-workspace-tab="${ids[1]}"]')`);
    assert.equal(articles.has(ids[1]),false);
    await select('library');
    await evaluate("document.getElementById('articleSearch').value='不存在';document.getElementById('articleSearch').dispatchEvent(new Event('input'))");
    await wait("document.querySelectorAll('[data-article-open]').length===0");
    await evaluate("document.getElementById('articleSearch').value='';document.getElementById('articleSearch').dispatchEvent(new Event('input'))");
    await wait("document.querySelectorAll('[data-article-open]').length===1");
    await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify('# 日文原文\r\n本文の行\n')}],'旅のノート.md',{type:'text/markdown'}));dt.items.add(new File([${JSON.stringify('日本語のテキスト\n')}],'短い手紙.txt',{type:'text/plain'}));const el=document.getElementById('articleFileInput');el.files=dt.files;el.dispatchEvent(new Event('change'));})()`);
    await wait("document.querySelectorAll('.article-editor').length===3");
    await wait("[...document.querySelectorAll('.article-save-state')].every(el=>el.textContent==='已保存')");
    const imported=[...articles.values()].find(a=>a.title==='旅のノート');
    assert(imported);assert.equal(imported.content,'# 日文原文\r\n本文の行\n');
    await select(imported.id);
    assert.equal(await evaluate(`document.getElementById('article-panel-${imported.id}').querySelector('.article-preview h1').textContent`),'日文原文');
    assert.equal(await evaluate(`document.getElementById('body-${imported.id}').hidden`),true);
    assert.equal(articles.get(imported.id).content,'# 日文原文\r\n本文の行\n');
    const callsBeforeReadingSelection={tts:ttsCalls,ai:explainCalls};
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${imported.id}');const text=node.querySelector('.article-preview p').firstChild;const range=document.createRange();range.selectNodeContents(text);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));node.querySelector('.article-fill').click();})()`);
    assert.equal(await evaluate("document.getElementById('textInput').value"),'本文の行');
    assert.equal(ttsCalls,callsBeforeReadingSelection.tts);assert.equal(explainCalls,callsBeforeReadingSelection.ai);
    console.log('PASS imported Markdown opens rendered reading view, retains source and fills only selected visible text');
    await select('library');
    await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array([255,254,0,0])],'bad.txt'));const el=document.getElementById('articleFileInput');el.files=dt.files;el.dispatchEvent(new Event('change'));})()`);
    await wait("document.getElementById('workspaceNotice').textContent.includes('UTF-8')");
    console.log('PASS closing preserves article; confirmed deletion, search, multi-file import and encoding errors');

    await select(ids[0]);
    await evaluate("document.getElementById('rightResizer').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}))");
    assert.equal(await evaluate("getComputedStyle(document.documentElement).getPropertyValue('--sidebar-right-width').trim()"),'355px');
    await evaluate("document.getElementById('rightResizer').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))");
    assert.equal(await evaluate("getComputedStyle(document.documentElement).getPropertyValue('--sidebar-right-width').trim()"),'345px');
    const shotDir=path.join(root,'docs/review/articles-workbench');fs.mkdirSync(shotDir,{recursive:true});
    async function screenshot(name){const image=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(shotDir,name+'.png'),Buffer.from(image.data,'base64'));}
    await select('library');await wait("document.querySelectorAll('[data-article-open]').length===3");
    await screenshot('library-light');
    await select(ids[0]);
    const readingText='> IP 解决“数据怎么送到一台主机”，端口解决“送给这台主机上的哪个进程”，TCP/UDP 解决“两个进程之间按什么规则传输数据”。\n\n---\n\n## 1. 端口号\n\n传输层最重要的抽象之一就是：\n\n```\nIP 地址 + 端口号\n```\n\nIP 定位主机，端口定位进程/服务。\n\n端口号是 16 bit：\n\n```\n0 ~ 65535\n```\n\n## 読書ノート\n\n日本語の一行目。\n二行目もそのまま読む。\n\n- **原文を保存**：編集は自動保存\n- `選択した文章`を音声入力へ\n\n';
    await input(ids[0],'.article-title-input','端口与传输层 · 阅读笔记');
    await input(ids[0],'.article-body',readingText.repeat(5));
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='已保存'`);
    assert.equal(await evaluate(`!!document.getElementById('article-panel-${ids[0]}').querySelector('.article-mode-live')`),true,'live preview editing must be available');
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');getSelection().removeAllRanges();node.querySelector('.article-mode-live').click();node.querySelector('.article-live h2').click();})()`);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').value`),'## 1. 端口号');
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelectorAll('.article-live textarea').length`),1);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live blockquote').textContent.includes('IP 解决')`),true);
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');const el=node.querySelector('.article-live-input');window.activeLiveInput=el;el.dispatchEvent(new CompositionEvent('compositionstart'));el.value='## 変更後の見出し';el.setSelectionRange(4,4);el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));})()`);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent.includes('输入中')`),true);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input')===window.activeLiveInput && window.activeLiveInput.selectionStart===4 && document.activeElement===window.activeLiveInput`),true);
    await evaluate(`window.activeLiveInput.dispatchEvent(new CompositionEvent('compositionend'));window.activeLiveInput.blur()`);
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live h2')?.textContent==='変更後の見出し'`);
    const liveText=readingText.repeat(5).replace('## 1. 端口号','## 変更後の見出し');
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='已保存'`);
    assert.equal(articles.get(ids[0]).content,liveText);
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live p').click()`);
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'z',code:'KeyZ',windowsVirtualKeyCode:90,modifiers:2});
    await send('Input.dispatchKeyEvent',{type:'keyUp',key:'z',code:'KeyZ',windowsVirtualKeyCode:90,modifiers:2});
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').value`),readingText.repeat(5),'undo must restore an edit after leaving its paragraph');
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'y',code:'KeyY',windowsVirtualKeyCode:89,modifiers:2});
    await send('Input.dispatchKeyEvent',{type:'keyUp',key:'y',code:'KeyY',windowsVirtualKeyCode:89,modifiers:2});
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').value`),liveText);
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');node.querySelector('.article-live blockquote').click();node.querySelector('.article-live').style.width='180px';})()`);
    assert.equal(await evaluate(`(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const input=document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input');return input.scrollHeight<=input.clientHeight;})()`),true,'width changes must refit source without waiting for a save or another input');
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live').style.width=''`);
    // Editing a block near the end must lead to that block in reading mode, not the page top.
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');const heads=node.querySelectorAll('.article-live h2');heads[heads.length-1].click();node.querySelector('.article-live-input').setSelectionRange(3,3);node.querySelector('.article-mode-read').click();})()`);
    assert.equal(await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');const heads=node.querySelectorAll('.article-preview h2');const heading=heads[heads.length-1],view=node.querySelector('.article-preview');return view.scrollTop>0 && heading.getBoundingClientRect().top>=view.getBoundingClientRect().top-2 && heading.getBoundingClientRect().top<view.getBoundingClientRect().bottom;})()`),true,'reading must show the edited heading');
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-mode-live').click()`);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').value`),'## 読書ノート');
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').selectionStart`),3);
    await select('ai');await select(ids[0]);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').selectionStart`),3);
    await screenshot('live-light');
    console.log('PASS live editing preserves source, IME input and caret; reading follows the edited block');
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live').dispatchEvent(new Event('scroll'))`);
    const liveScroll=await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live').scrollTop`);
    await evaluate("document.body.dataset.ready='reloading'");await send('Page.reload');
    await wait("document.body?.dataset.ready==='true'");
    await wait(`!!document.getElementById('article-panel-${ids[0]}')?.querySelector('.article-live-input')`);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').value`),'## 読書ノート');
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').selectionStart`),3);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live').scrollTop`),liveScroll);
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').setSelectionRange(0,0)`);
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowUp',code:'ArrowUp',windowsVirtualKeyCode:38});
    await send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowUp',code:'ArrowUp',windowsVirtualKeyCode:38});
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').value`),'```\n0 ~ 65535\n```');
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowDown',code:'ArrowDown',windowsVirtualKeyCode:40});
    await send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowDown',code:'ArrowDown',windowsVirtualKeyCode:40});
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-live-input').value`),'## 読書ノート');
    await select(imported.id);
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${imported.id}');node.querySelector('.article-mode-live').click();node.querySelector('.article-live p').click();const el=node.querySelector('.article-live-input');el.value=${JSON.stringify('本文の行\n追加した行')};el.dispatchEvent(new InputEvent('input',{bubbles:true}));el.blur();})()`);
    await wait(`document.getElementById('article-panel-${imported.id}').querySelector('.article-save-state').textContent==='已保存'`);
    assert.equal(articles.get(imported.id).content,'# 日文原文\r\n本文の行\r\n追加した行\n');
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${imported.id}');node.querySelector('.article-add-paragraph').click();const el=node.querySelector('.article-live-input');el.value='## 新段落';el.dispatchEvent(new InputEvent('input',{bubbles:true}));el.blur();})()`);
    await wait(`document.getElementById('article-panel-${imported.id}').querySelector('.article-live h2')?.textContent==='新段落'`);
    await wait(`document.getElementById('article-panel-${imported.id}').querySelector('.article-save-state').textContent==='已保存'`);
    assert.equal(articles.get(imported.id).content,'# 日文原文\r\n本文の行\r\n追加した行\n\r\n## 新段落');
    const beforeLiveFill={tts:ttsCalls,ai:explainCalls};
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${imported.id}');const range=document.createRange();range.selectNodeContents(node.querySelector('.article-live p'));getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new Event('selectionchange'));node.querySelector('.article-fill').click();getSelection().removeAllRanges();})()`);
    assert.equal(await evaluate("document.getElementById('textInput').value"),'本文の行\n追加した行');
    assert.deepEqual({tts:ttsCalls,ai:explainCalls},beforeLiveFill);
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${imported.id}');node.querySelector('.article-live p').click();const input=node.querySelector('.article-live-input');input.setSelectionRange(input.value.length,input.value.length);})()`);
    await send('Input.insertText',{text:'\n'+('新しく入力した一行。\n').repeat(28)});
    assert.equal(await evaluate(`(()=>{const node=document.getElementById('article-panel-${imported.id}'),input=node.querySelector('.article-live-input'),viewport=node.querySelector('.article-live');return input.getBoundingClientRect().bottom<=viewport.getBoundingClientRect().bottom;})()`),true,'typing must keep the final line and caret visible');
    await select(ids[0]);
    console.log('PASS live mode restores on reload, keyboard moves between blocks, CRLF survives editing and new paragraphs; selected text fills without sending');
    await input(ids[0],'.article-body',readingText.repeat(5));
    await wait(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-save-state').textContent==='已保存'`);
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');node.querySelector('.article-body').scrollTop=160;node.querySelector('.article-mode-read').click();node.querySelector('.article-preview').scrollTop=220;node.querySelector('.article-preview').dispatchEvent(new Event('scroll'));})()`);
    const previewScroll=await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-preview').scrollTop`);
    assert.equal(previewScroll,220);
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-mode-edit').click()`);
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').scrollTop`),160);
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-mode-read').click()`);
    const switchedScroll=await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-preview').scrollTop`);
    assert(switchedScroll>0,'source to reading must follow the current source position');
    await select('ai');
    await evaluate("document.body.dataset.ready='reloading'");await send('Page.reload');
    await wait("document.body?.dataset.ready==='true'");
    await wait(`!!document.querySelector('[data-workspace-tab="${ids[0]}"]')`);
    await wait("document.querySelector('[data-workspace-tab=\"ai\"]').getAttribute('aria-selected')==='true'");
    await select(ids[0]);
    assert.equal(await evaluate(`document.getElementById('body-${ids[0]}').hidden`),true);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-preview').scrollTop`),switchedScroll);
    assert.equal(articles.get(ids[0]).content,readingText.repeat(5));
    const beforeRenderedFill={tts:ttsCalls,ai:explainCalls};
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');const paragraph=[...node.querySelectorAll('.article-preview p')].find(p=>p.textContent.startsWith('日本語の一行目。'));const range=document.createRange();range.selectNodeContents(paragraph);getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new Event('selectionchange'));node.querySelector('.article-fill').click();})()`);
    assert.equal(await evaluate("document.getElementById('textInput').value"),'日本語の一行目。\n二行目もそのまま読む。');
    assert.equal(ttsCalls,beforeRenderedFill.tts);assert.equal(explainCalls,beforeRenderedFill.ai);
    await evaluate(`(()=>{const node=document.getElementById('article-panel-${ids[0]}');const range=document.createRange();range.selectNodeContents(document.querySelector('.workspace-toolbar'));getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new Event('selectionchange'));})()`);
    assert.equal(await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-fill').disabled`),true);
    await evaluate(`getSelection().removeAllRanges();document.getElementById('article-panel-${ids[0]}').querySelector('.article-preview').scrollTop=0`);
    console.log('PASS reading follows source position and retains scroll across tabs and reload; rendered selection preserves newlines');
    await screenshot('desktop-light');
    await evaluate("document.getElementById('settingsBtn').click();document.querySelector('[data-theme=\"dark\"]').click();document.getElementById('modalCloseBtn').click()");
    await screenshot('desktop-dark');
    await evaluate(`document.getElementById('article-panel-${ids[0]}').querySelector('.article-mode-live').click()`);
    await screenshot('live-dark');
    await select('ai');await screenshot('ai-dark');await select(ids[0]);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
    await evaluate("document.getElementById('aiPanelBtn').click();document.getElementById('workspaceAddBtn').click()");
    await wait("document.getElementById('chatMain').inert===true");
    await select(ids[0]);
    assert.equal(await evaluate("document.getElementById('explainSection').hidden"),false);
    assert.equal(await evaluate("getComputedStyle(document.getElementById('rightResizer')).display"),'none');
    await screenshot('mobile-dark');
    await evaluate("document.getElementById('aiCloseBtn').click()");
    assert.equal(await evaluate("document.getElementById('chatMain').inert"),false);
    assert.equal(await evaluate("document.documentElement.scrollWidth<=390"),true);
    console.log('PASS theme, width reset and narrow drawer layout; screenshots saved');
    assert.equal(await evaluate(`(async()=>{const saved=sessionStorage.getItem('tts_article_draft_owner');const {claimDraftOwner}=await import('/article-drafts.js');const duplicate=await claimDraftOwner();const unique=duplicate.owner!==saved;duplicate.dispose();sessionStorage.setItem('tts_article_draft_owner',saved);return unique;})()`),true);
    console.log('PASS duplicated browser tab session identity receives an isolated draft owner');
    account=null;
    await evaluate("document.body.dataset.ready='reloading'");
    await send('Page.reload');await wait("document.body?.dataset.ready==='true'");
    await evaluate("document.getElementById('aiPanelBtn').click();document.getElementById('workspaceAddBtn').click()");
    assert.equal(await evaluate("document.getElementById('articleLibrary').textContent.includes('登录后')"),true);
    assert.equal(await evaluate("document.querySelectorAll('.article-editor').length"),0);
    assert.deepEqual(exceptions,[]);
    console.log('PASS signed-out library prompt and clean browser runtime');
  }finally{await browser?.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
